name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Render Deploy Hook
      run: curl "${{ secrets.RENDER_DEPLOY_HOOK }}"
